# 项目端口号
server:
  port: 8080

spring:
  application:
    name: seckill-demo
  # thymeleaf 配置
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
    hikari:
      # 连接池名称
      pool-name: DateHikariCP
      minimum-idle: 5
      # 连接超时时间
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 3000
      # 测试链接sql语句
      connection-test-query: SELECT 1

springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Mybatis-plus配置
mybatis-plus:
  # mapper位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 实体类包名
  type-aliases-package: org.wby.seckill.pojo

# Mybatis-plus
logging:
  level:
    org.wby.seckill.mapper: debug