spring:
  application:
    name: seckill-demo
  # thymeleaf ??
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
    hikari:
      # ?????
      pool-name: DateHikariCP
      minimum-idle: 5
      # ?????????????10???600000?
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 3000
      # ?????????????
      connection-test-query: SELECT 1

# Mybatis-plus??
mybatis-plus:
  # ??Mapper.xml ????
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # ??Mybatis-plus??????????????????
  type-aliases-package: org.wby.seckill.pojo

# Mybatis-plus SQL??????????????Mapper.xml?????
logging:
  level:
    org.wby.seckill.mapper: debug